/**
 * Dữ liệu 64 tỉnh/thành phố Việt Nam với tọa độ SVG, thông tin và đặc sản
 */

export interface Province {
  id: string
  name: string
  printName: string
  shortName: string
  region: string
  description: string
  specialties: Specialty[]
  svgPath: string
  // Tọa độ tâm để hiển thị tên tỉnh
  centerX: number
  centerY: number
  // Hệ số zoom cho phóng to
  zoomScale?: number
  zoomX?: number
  zoomY?: number
}

export interface Specialty {
  name: string
  description: string
  emoji?: string
}

export const provinces: Province[] = [
  // listing the 64 actual provinces; placeholder entries removed so search will
  // operate over real names. Additional provinces can be appended below.
{
  id: "ha-giang",
  name: "Hà Giang",
    shortName: "HG",
    printName: "Tỉnh Hà Giang",
    region: "Miền Bắc",
    description: "Tỉnh cao nguyên ở phía Bắc, nổi tiếng với cảnh quan đơi núi tuyệt đẹp và vai trò lịch sử.",
    specialties: [
      { name: "Maize (Bắp cây)", description: "Bắp ngô tươi, ngọt từ vùng cao", emoji: "🌽" },
      { name: "Đinh hương", description: "Gia vị quý giá từ Hà Giang", emoji: "🌸" },
      { name: "Mật ong rừng", description: "Mật ong nguyên chất từ khu bảo tồn", emoji: "🍯" },
    ],
    svgPath: "M 420 70 Q 440 60 450 80 Q 445 100 420 95 Z",
    centerX: 435,
    centerY: 82,
  },
  {
    id: "cao-bang",
    name: "Cao Bằng",
    shortName: "CB",
    printName: "Tỉnh Cao Bằng",
    region: "Miền Bắc",
    description: "Vùng đất giáp biên giới với Trung Quốc, có quần thể rừng sâu và dân tộc độc đáo.",
    specialties: [
      { name: "Thịt dê rừng", description: "Thịt dê nuôi trong rừng sâu, thơm ngon", emoji: "🐐" },
      { name: "Sung Cao Bằng", description: "Loại nấm quý hiếm từ các rừng nguyên sinh", emoji: "🍄" },
      { name: "Tre Cao Bằng", description: "Đặc sản tre già để ghép hay xây dựng", emoji: "🎋" },
    ],
    svgPath: "M 450 50 Q 475 45 485 70 Q 475 85 450 80 Z",
    centerX: 467,
    centerY: 67,
  },
  {
    id: "bac-kan",
    name: "Bắc Kạn",
    shortName: "BK",
    printName: "Tỉnh Bắc Kạn",
    region: "Miền Bắc",
    description: "Tỉnh nhỏ trong vùng Đông Bắc Việt Nam, nổi tiếng với hồ Ba Bể xinh đẹp.",
    specialties: [
      { name: "Cá Bắc Kạn", description: "Cá hồ Ba Bể ngọt, tươi sống", emoji: "🐟" },
      { name: "Dâu tây", description: "Dâu tây từ vùng cao Bắc Kạn", emoji: "🍓" },
      { name: "Cà phê góc", description: "Cà phê trồng ở vùng cao", emoji: "☕" },
    ],
    svgPath: "M 420 85 Q 435 75 450 85 Q 440 105 420 100 Z",
    centerX: 435,
    centerY: 90,
  },
  {
    id: "lang-son",
    name: "Lạng Sơn",
    shortName: "LS",
    printName: "Tỉnh Lạng Sơn",
    region: "Miền Bắc",
    description: "Tỉnh biên giới giáp Trung Quốc, có nền văn hóa phong phú và lịch sử sâu sắc.",
    specialties: [
      { name: "Gốm Bát Tràng", description: "Gốm sứ truyền thống Lạng Sơn", emoji: "🏺" },
      { name: "Thịt đặc sản", description: "Thịt các loại động vật nuôi địa phương", emoji: "🍖" },
      { name: "Bánh chưng", description: "Bánh chưng truyền thống", emoji: "🍲" },
    ],
    svgPath: "M 460 65 Q 485 55 500 80 Q 485 100 460 90 Z",
    centerX: 480,
    centerY: 78,
  },
  {
    id: "tuyen-quang",
    name: "Tuyên Quang",
    shortName: "TQ",
    printName: "Tỉnh Tuyên Quang",
    region: "Miền Bắc",
    description: "Tỉnh Đông Bắc Việt Nam có nền nông nghiệp phát triển, nổi tiếng với các sản phẩm nông sản.",
    specialties: [
      { name: "Chè Tuyên Quang", description: "Chè xanh lá từ vùng cao", emoji: "🍵" },
      { name: "Nông sản sạch", description: "Rau quả hữu cơ trồng thủ công", emoji: "🥦" },
      { name: "Mủ cao", description: "Sản phẩm từ mủ cây cao dặm", emoji: "🌳" },
    ],
    svgPath: "M 400 95 Q 420 85 435 100 Q 420 115 400 110 Z",
    centerX: 415,
    centerY: 103,
  },
  {
    id: "thai-nguyen",
    name: "Thái Nguyên",
    shortName: "TN",
    printName: "Tỉnh Thái Nguyên",
    region: "Miền Bắc",
    description: "Tỉnh công nghiệp của Đông Bắc Việt Nam, trung tâm sản xuất chè nổi tiếng.",
    specialties: [
      { name: "Chè Thái Nguyên", description: "Chè lứu danh tiếng, hương thơm độc đáo", emoji: "🍵" },
      { name: "Than đá", description: "Sản phẩm khai thác từ mỏ", emoji: "⚫" },
      { name: "Cánh gà nướng", description: "Cánh gà nướng thơm ngon", emoji: "🍗" },
    ],
    svgPath: "M 410 105 Q 430 95 445 110 Q 430 125 410 120 Z",
    centerX: 427,
    centerY: 113,
  },
  {
    id: "bac-giang",
    name: "Bắc Giang",
    shortName: "BG",
    printName: "Tỉnh Bắc Giang",
    region: "Miền Bắc",
    description: "Tỉnh Bắc Giang nổi tiếng với sản xuất quả nhãn, lựu và các sản phẩm nông nghiệp.",
    specialties: [
      { name: "Nhãn Bến Tre", description: "Nhãn ngọt, đậu giòn từ vùng cao", emoji: "🍌" },
      { name: "Lựu Bắc Giang", description: "Lựu đỏ ngọt, múi cơm đầy", emoji: "💎" },
      { name: "Ớt sạch", description: "Ớt trồng theo tiêu chuẩn hữu cơ", emoji: "🌶️" },
    ],
    svgPath: "M 425 110 Q 445 100 460 120 Q 445 135 425 130 Z",
    centerX: 442,
    centerY: 120,
  },
  {
    id: "bac-ninh",
    name: "Bắc Ninh",
    shortName: "BN",
    printName: "Tỉnh Bắc Ninh",
    region: "Miền Bắc",
    description: "Tỉnh có truyền thống thủ công mỹ nghệ lâu đời, nổi tiếng với gơm Bát Tràng.",
    specialties: [
      { name: "Gốm Bát Tràng", description: "Gốm sứ cổ truyền nổi tiếng thế giới", emoji: "🏺" },
      { name: "Dâu Bắc Ninh", description: "Dâu tươi sạch từ nông trại hiện đại", emoji: "🍓" },
      { name: "Bánh bao Bắc Ninh", description: "Bánh bao truyền thống mềm, thơm", emoji: "🥟" },
    ],
    svgPath: "M 420 120 Q 440 110 455 130 Q 440 145 420 140 Z",
    centerX: 437,
    centerY: 130,
  },
  {
    id: "phu-tho",
    name: "Phú Thọ",
    shortName: "PT",
    printName: "Tỉnh Phú Thọ",
    region: "Miền Bắc",
    description: "Tỉnh có nền văn hóa Việt cổ sâu sắc, địa bàn của các tộc Kinh và Tày.",
    specialties: [
      { name: "Mứt Phú Thọ", description: "Mứt truyền thống từ hoa quả thơm nức", emoji: "🍒" },
      { name: "Nước mắm", description: "Nước mắm đặc sản từ cá cá bò", emoji: "🐟" },
      { name: "Nước tương lên men", description: "Tương tuyền từ đậu phộngtrắng", emoji: "🫙" },
    ],
    svgPath: "M 380 120 Q 405 110 420 130 Q 405 150 380 140 Z",
    centerX: 400,
    centerY: 130,
  },
  {
    id: "quang-ninh",
    name: "Quảng Ninh",
    shortName: "QN",
    printName: "Tỉnh Quảng Ninh",
    region: "Miền Bắc",
    description: "Tỉnh ven biển nổi tiếng với Vịnh Hạ Long, nông nghiệp và thủy sản phát triển.",
    specialties: [
      { name: "Cua Hạ Long", description: "Cua biển tươi sống, vị ngon đặc biệt", emoji: "🦀" },
      { name: "Mực", description: "Mực tươi từ vùng biển Hạ Long", emoji: "🦑" },
      { name: "Nho Quảng Ninh", description: "Nho không hạt trắng", emoji: "🍇" },
    ],
    svgPath: "M 450 100 Q 475 90 490 110 Q 475 125 450 120 Z",
    centerX: 470,
    centerY: 110,
  },
  {
    id: "vinh-phuc",
    name: "Vĩnh Phúc",
    shortName: "VP",
    printName: "Tỉnh Vĩnh Phúc",
    region: "Miền Bắc",
    description: "Tỉnh có nền sản xuất rau quả, lâm sản phát triển, gần Hà Nội.",
    specialties: [
      { name: "Tơ sen Vĩnh Phúc", description: "Lụa nguyên chất từ tơ tằm địa phương", emoji: "👔" },
      { name: "Rau sạch", description: "Rau quả hữu cơ sạch sẽ", emoji: "🥬" },
      { name: "Mật ong rừng tự nhiên", description: "Mật ong 100% từ khu tự nhiên", emoji: "🍯" },
    ],
    svgPath: "M 400 110 Q 415 105 425 120 Q 415 135 400 130 Z",
    centerX: 412,
    centerY: 120,
  },
  {
    id: "yen-bai",
    name: "Yên Bái",
    shortName: "YB",
    printName: "Tỉnh Yên Bái",
    region: "Miền Bắc",
    description: "Tỉnh vùng cao Đông Bắc, có nền nông nghiệp lâm sản phong phú.",
    specialties: [
      { name: "Lúa Yên Bái", description: "Lúa hạt nhỏ, hương thơm độc đáo", emoji: "🌾" },
      { name: "Dâu tây vùng cao", description: "Dâu tây tươi sạch từ nông trại", emoji: "🍓" },
      { name: "Mật ong", description: "Mật ong từ rừng Yên Bái", emoji: "🍯" },
    ],
    svgPath: "M 350 110 Q 375 100 390 120 Q 375 140 350 130 Z",
    centerX: 370,
    centerY: 120,
  },
  {
    id: "son-la",
    name: "Sơn La",
    shortName: "SL",
    printName: "Tỉnh Sơn La",
    region: "Miền Bắc",
    description: "Tỉnh vùng Tây Bắc nổi tiếng với sơn màu đen, thủ công mỹ nghệ.",
    specialties: [
      { name: "Cà phê Sơn La", description: "Cà phê arabica từ vùng cao 1500m", emoji: "☕" },
      { name: "Chanh leo", description: "Chanh leo tươi từ nông trại", emoji: "🍓" },
      { name: "Sơn đen", description: "Sơn truyền thống từ lâu đời", emoji: "⚫" },
    ],
    svgPath: "M 330 100 Q 360 85 380 110 Q 360 135 330 120 Z",
    centerX: 355,
    centerY: 108,
  },
  {
    id: "dien-bien",
    name: "Điện Biên",
    shortName: "DB",
    printName: "Tỉnh Điện Biên",
    region: "Miền Bắc",
    description: "Tỉnh xa xôi ở Tây Bắc, nơi xảy ra trận Điện Biên Phủ lịch sử.",
    specialties: [
      { name: "Cà phê Điện Biên", description: "Cà phê robusta từ vùng cao", emoji: "☕" },
      { name: "Hành tím", description: "Hành tím trồng tại Điện Biên", emoji: "🧅" },
      { name: "Lúa gạo", description: "Gạo từ ruộng thửa bậc thang", emoji: "🌾" },
    ],
    svgPath: "M 310 80 Q 345 65 360 100 Q 340 125 310 110 Z",
    centerX: 335,
    centerY: 95,
  },
  {
    id: "lai-chau",
    name: "Lai Châu",
    shortName: "LC",
    printName: "Tỉnh Lai Châu",
    region: "Miền Bắc",
    description: "Tỉnh vùng Tây Bắc xa xôi, địa bàn của các dân tộc Thái và Mường.",
    specialties: [
      { name: "Gạo nước", description: "Gạo từ vùng cao Lai Châu", emoji: "🌾" },
      { name: "Dâu tây", description: "Dâu tây sạch từ nông trại", emoji: "🍓" },
      { name: "Thịt dê", description: "Thịt dê rừng thương phẩm", emoji: "🐐" },
    ],
    svgPath: "M 300 70 Q 330 55 350 90 Q 325 115 300 100 Z",
    centerX: 325,
    centerY: 83,
  },

  // ===== MIỀN TRUNG =====
  {
    id: "hoa-binh",
    name: "Hòa Bình",
    shortName: "HB",
    printName: "Tỉnh Hòa Bình",
    region: "Miền Trung",
    description: "Tỉnh có nhiều dân tộc, nổi tiếng với thủy điện Hòa Bình.",
    specialties: [
      { name: "Cà phê Hòa Bình", description: "Cà phê từ nông trại độc lập", emoji: "☕" },
      { name: "Gạo lứt", description: "Gạo lứt chuyên biệt từ Hòa Bình", emoji: "🌾" },
      { name: "Lợn cắp nách", description: "Lợn rừng nuôi thâm canh", emoji: "🐷" },
    ],
    svgPath: "M 350 140 Q 380 130 395 160 Q 380 175 350 165 Z",
    centerX: 372,
    centerY: 152,
  },
  {
    id: "thanh-hoa",
    name: "Thanh Hóa",
    shortName: "TH",
    printName: "Tỉnh Thanh Hóa",
    region: "Miền Trung",
    description: "Tỉnh lịch sử giáp biển, nổi tiếng với Tam Đảo, Thanh Chương.",
    specialties: [
      { name: "Cua Thanh Hóa", description: "Cua biển ngon, vị đặc sắc", emoji: "🦀" },
      { name: "Nước mắm Thanh Hóa", description: "Nước mắm độc đáo từ cá bề bề", emoji: "🐟" },
      { name: "Lợn Thanh Hóa", description: "Thịt lợn thương phẩm, chất lượng", emoji: "🐷" },
    ],
    svgPath: "M 380 160 Q 410 150 425 180 Q 410 200 380 190 Z",
    centerX: 402,
    centerY: 175,
  },
  {
    id: "nghe-an",
    name: "Nghệ An",
    shortName: "NA",
    printName: "Tỉnh Nghệ An",
    region: "Miền Trung",
    description: "Tỉnh lớn ở Bắc Trung Bộ, có nền sản xuất nông lâm phủc phát triển.",
    specialties: [
      { name: "Mộc Châu", description: "Sữa từ trang trại hiện đại", emoji: "🥛" },
      { name: "Cà phê Mộc Châu", description: "Cà phê arabica từ vùng cao", emoji: "☕" },
      { name: "Thanh sương", description: "Thanh sương tươi sạch", emoji: "🍵" },
    ],
    svgPath: "M 410 190 Q 440 180 455 210 Q 440 230 410 220 Z",
    centerX: 432,
    centerY: 205,
  },
  {
    id: "ha-tinh",
    name: "Hà Tĩnh",
    shortName: "HT",
    printName: "Tỉnh Hà Tĩnh",
    region: "Miền Trung",
    description: "Tỉnh ven biển ở Bắc Trung Bộ, nổi tiếng với mắm tôm.",
    specialties: [
      { name: "Mắm tôm Hà Tĩnh", description: "Mắm tôm độc đáo, vị umami", emoji: "🦐" },
      { name: "Tôm Hà Tĩnh", description: "Tôm biển tươi sống", emoji: "🦐" },
      { name: "Muối Hà Tĩnh", description: "Muối biển nguyên chất", emoji: "🧂" },
    ],
    svgPath: "M 420 210 Q 450 200 465 230 Q 450 250 420 240 Z",
    centerX: 442,
    centerY: 225,
  },
  {
    id: "quang-binh",
    name: "Quảng Bình",
    shortName: "QB",
    printName: "Tỉnh Quảng Bình",
    region: "Miền Trung",
    description: "Tỉnh ven biển, nổi tiếng với hang Sơn Đoòng và hải sản ngon.",
    specialties: [
      { name: "Cua Quảng Bình", description: "Cua tinh tú từ biển Quảng Bình", emoji: "🦀" },
      { name: "Mực biển", description: "Mực tươi sống đông lạnh", emoji: "🦑" },
      { name: "Phèn Quảng Bình", description: "Phèn tươi (cua cà chua)", emoji: "🧂" },
    ],
    svgPath: "M 440 230 Q 470 220 485 250 Q 470 270 440 260 Z",
    centerX: 462,
    centerY: 245,
  },
  {
    id: "quang-tri",
    name: "Quảng Trị",
    shortName: "QT",
    printName: "Tỉnh Quảng Trị",
    region: "Miền Trung",
    description: "Tỉnh ven biển Miền Trung, nổi tiếng với Cái Nước và Du Lịch.",
    specialties: [
      { name: "Cá điêu hồng", description: "Cá điêu hồng tươi từ sông Thạch Hãn", emoji: "🐟" },
      { name: "Nước mắm", description: "Nước mắm cá chuồn", emoji: "🐟" },
      { name: "Chè Ô Long", description: "Chè Ô Long từ vùng cao", emoji: "🍵" },
    ],
    svgPath: "M 460 250 Q 490 240 505 270 Q 490 290 460 280 Z",
    centerX: 482,
    centerY: 265,
  },
  {
    id: "thua-thien-hue",
    name: "Thừa Thiên-Huế",
    shortName: "TT-HUE",
    printName: "Tỉnh Thừa Thiên-Huế",
    region: "Miền Trung",
    description: "Tỉnh văn hóa Trung Bộ, nơi có các di tích lịch sử nổi tiếng.",
    specialties: [
      { name: "Com Huế", description: "Cơm tấm Huế với các loại nước dùng", emoji: "🍚" },
      { name: "Bánh hoai", description: "Bánh hoai đặc sản Huế", emoji: "🥘" },
      { name: "Mực Huế", description: "Mực tươi từ sông Hương", emoji: "🦑" },
    ],
    svgPath: "M 480 280 Q 510 270 525 300 Q 510 320 480 310 Z",
    centerX: 502,
    centerY: 295,
  },
  {
    id: "da-nang",
    name: "Đà Nẵng",
    shortName: "DN",
    printName: "Thành phố Đà Nẵng",
    region: "Miền Trung",
    description: "Thành phố biển hiện đại, trung tâm kinh tế Miền Trung.",
    specialties: [
      { name: "Bánh hoai Đà Nẵng", description: "Bánh hoai với thịt nướng đặc sắc", emoji: "🥘" },
      { name: "Cá nướng", description: "Cá nướng muối Đà Nẵng", emoji: "🐟" },
      { name: "Mít Đà Nẵng", description: "Mít ngon từ khu vực Ngu Hành Sơn", emoji: "🌳" },
    ],
    svgPath: "M 520 310 Q 540 305 550 325 Q 540 340 520 335 Z",
    centerX: 535,
    centerY: 320,
  },
  {
    id: "quang-nam",
    name: "Quảng Nam",
    shortName: "QM",
    printName: "Tỉnh Quảng Nam",
    region: "Miền Trung",
    description: "Tỉnh lớn Miền Trung, nổi tiếng với bàn giao Hội An cổ kính.",
    specialties: [
      { name: "Bánh vạc", description: "Bánh vạc còn gọi là bánh ống Hội An", emoji: "🥟" },
      { name: "Cao lau", description: "Cao lâu đặc sản Hội An", emoji: "🍜" },
      { name: "Mực nướng", description: "Mực nướng muối từ An Hòa", emoji: "🦑" },
    ],
    svgPath: "M 500 330 Q 535 320 550 350 Q 535 370 500 360 Z",
    centerX: 525,
    centerY: 345,
  },
  {
    id: "quang-ngai",
    name: "Quảng Ngãi",
    shortName: "QG",
    printName: "Tỉnh Quảng Ngãi",
    region: "Miền Trung",
    description: "Tỉnh ven biển có nền sản xuất nông lâm phủc phát triển.",
    specialties: [
      { name: "Tôm hùm", description: "Tôm hùm tươi từ vùng biển", emoji: "🦐" },
      { name: "Cua Quảng Ngãi", description: "Cua biển chất lượng cao", emoji: "🦀" },
      { name: "Nước mắm Quảng Ngãi", description: "Nước mắm từ cá chuồn", emoji: "🐟" },
    ],
    svgPath: "M 520 360 Q 555 350 570 380 Q 555 400 520 390 Z",
    centerX: 542,
    centerY: 375,
  },
  {
    id: "binh-dinh",
    name: "Bình Định",
    shortName: "BD",
    printName: "Tỉnh Bình Định",
    region: "Miền Trung",
    description: "Tỉnh ven biển, nổi tiếng với Quy Nhơn và hải sản.",
    specialties: [
      { name: "Cá nướng Quy Nhơn", description: "Cá nướng muối vàng ươm", emoji: "🐟" },
      { name: "Tôm Bình Định", description: "Tôm tươi sống từ biển Quy Nhơn", emoji: "🦐" },
      { name: "Mực Bình Định", description: "Mực tươi hoặc khô từ Quy Nhơn", emoji: "🦑" },
    ],
    svgPath: "M 540 380 Q 575 370 590 400 Q 575 420 540 410 Z",
    centerX: 562,
    centerY: 395,
  },
  {
    id: "phu-yen",
    name: "Phú Yên",
    shortName: "PY",
    printName: "Tỉnh Phú Yên",
    region: "Miền Trung",
    description: "Tỉnh ven biển, địa bàn của các dân tộc Ê Đê và Kinh.",
    specialties: [
      { name: "Tôm Phú Yên", description: "Tôm tươi sống từ biển Tuy Hòa", emoji: "🦐" },
      { name: "Cá cơm Phú Yên", description: "Cá cơm tươi hoặc khô", emoji: "🐟" },
      { name: "Nước mắm cá trích", description: "Nước mắm từ cá trích", emoji: "🐟" },
    ],
    svgPath: "M 560 410 Q 595 400 610 430 Q 595 450 560 440 Z",
    centerX: 582,
    centerY: 425,
  },
  {
    id: "khanh-hoa",
    name: "Khánh Hòa",
    shortName: "KH",
    printName: "Tỉnh Khánh Hòa",
    region: "Miền Trung",
    description: "Tỉnh ven biển nổi tiếng với Nha Trang, du lịch và thủy sản.",
    specialties: [
      { name: "Tôm hùm Nha Trang", description: "Tôm hùm tươi sống đắt đỏ", emoji: "🦐" },
      { name: "Cá cơm", description: "Cá cơm sốt", emoji: "🐟" },
      { name: "Yến sào Nha Trang", description: "Yến sào từ hang Mỹ Khê", emoji: "🏠" },
    ],
    svgPath: "M 580 440 Q 615 430 630 460 Q 615 480 580 470 Z",
    centerX: 602,
    centerY: 455,
  },
  {
    id: "ninh-thuan",
    name: "Ninh Thuận",
    shortName: "NT",
    printName: "Tỉnh Ninh Thuận",
    region: "Miền Trung",
    description: "Tỉnh ven biển xa xôi, nổi tiếng với chuối, dứa và nước mắm.",
    specialties: [
      { name: "Nước mắm Ninh Thuận", description: "Nước mắm độc đáo từ cá chuồn", emoji: "🐟" },
      { name: "Chuối Ninh Thuận", description: "Chuối chín tự nhiên, ngon", emoji: "🍌" },
      { name: "Dứa Ninh Thuận", description: "Dứa ngọt, mọng nước", emoji: "🍍" },
    ],
    svgPath: "M 610 470 Q 645 460 660 490 Q 645 510 610 500 Z",
    centerX: 632,
    centerY: 485,
  },
  {
    id: "binh-thuan",
    name: "Bình Thuận",
    shortName: "BT",
    printName: "Tỉnh Bình Thuận",
    region: "Miền Trung",
    description: "Tỉnh ven biển xa xôi, nổi tiếng với nước mắm và hạt tiêu.",
    specialties: [
      { name: "Tôm Bình Thuận", description: "Tôm tươi từ biển Phan Thiết", emoji: "🦐" },
      { name: "Cá khô Phan Thiết", description: "Cá khô nổi tiếng", emoji: "🐟" },
      { name: "Nước mắm cá chuồn", description: "Nước mắm độc đáo", emoji: "🐟" },
    ],
    svgPath: "M 640 500 Q 675 490 690 520 Q 675 540 640 530 Z",
    centerX: 662,
    centerY: 515,
  },

  // ===== MIỀN NAM =====
  {
    id: "dong-nai",
    name: "Đồng Nai",
    shortName: "DN",
    printName: "Tỉnh Đồng Nai",
    region: "Miền Nam",
    description: "Tỉnh công nghiệp gần Hồ Chí Minh, nổi tiếng với sản xuất cao su.",
    specialties: [
      { name: "Dâu Đồng Nai", description: "Dâu tây sạch từ nông trại", emoji: "🍓" },
      { name: "Xoài Đồng Nai", description: "Xoài thơm ngon từ Cát Tiên", emoji: "🥭" },
      { name: "Sầu riêng Đồng Nai", description: "Sầu riêng ngoại phục từ Đồng Nai", emoji: "👑" },
    ],
    svgPath: "M 600 520 Q 635 510 650 540 Q 635 560 600 550 Z",
    centerX: 622,
    centerY: 535,
  },
  {
    id: "ba-ria-vung-tau",
    name: "Bà Rịa-Vũng Tàu",
    shortName: "BR-VT",
    printName: "Tỉnh Bà Rịa-Vũng Tàu",
    region: "Miền Nam",
    description: "Tỉnh ven biển, nổi tiếng với du lịch và hải sản tươi.",
    specialties: [
      { name: "Cá biển Vũng Tàu", description: "Cá biển tươi sống đông lạnh", emoji: "🐟" },
      { name: "Tôm hùm", description: "Tôm hùm tươi từ biển Vũng Tàu", emoji: "🦐" },
      { name: "Cua Vũng Tàu", description: "Cua tinh tú từ vùng biển", emoji: "🦀" },
    ],
    svgPath: "M 630 540 Q 665 530 680 560 Q 665 580 630 570 Z",
    centerX: 652,
    centerY: 555,
  },
  {
    id: "ho-chi-minh",
    name: "Hồ Chí Minh",
    shortName: "HCM",
    printName: "Thành phố Hồ Chí Minh",
    region: "Miền Nam",
    description: "Thành phố lớn nhất Việt Nam, trung tâm kinh tế Miền Nam.",
    specialties: [
      { name: "Bánh mỳ Sài Gòn", description: "Bánh mỳ giản dị nhưng ngon", emoji: "🥖" },
      { name: "Cơm tấm", description: "Cơm tấm với các loại nước dùng", emoji: "🍚" },
      { name: "Phở Sài Gòn", description: "Phở ngon tại các quán ăn", emoji: "🍲" },
    ],
    svgPath: "M 600 560 Q 635 550 650 580 Q 635 600 600 590 Z",
    centerX: 622,
    centerY: 575,
  },
  {
    id: "tay-ninh",
    name: "Tây Ninh",
    shortName: "TN",
    printName: "Tỉnh Tây Ninh",
    region: "Miền Nam",
    description: "Tỉnh ở Tây Nam Bộ, nổi tiếng với Núi Bà Đen.",
    specialties: [
      { name: "Cà phê Tây Ninh", description: "Cà phê robusta chất lượng cao", emoji: "☕" },
      { name: "Hạt tiêu Tây Ninh", description: "Hạt tiêu đen nguyên chất", emoji: "🌶️" },
      { name: "Dâu tây", description: "Dâu tây sạch từ nông trại", emoji: "🍓" },
    ],
    svgPath: "M 540 570 Q 575 560 590 590 Q 575 610 540 600 Z",
    centerX: 562,
    centerY: 585,
  },
  {
    id: "long-an",
    name: "Long An",
    shortName: "LA",
    printName: "Tỉnh Long An",
    region: "Miền Nam",
    description: "Tỉnh Đông Nam Bộ, nổi tiếng với canh tác lúa gạo.",
    specialties: [
      { name: "Gạo Long An", description: "Gạo thơm từ vùng lòng chảo", emoji: "🌾" },
      { name: "Chè xanh Long An", description: "Chè xanh từ vùng cao", emoji: "🍵" },
      { name: "Tôm Long An", description: "Tôm nuôi từ ao tôm địa phương", emoji: "🦐" },
    ],
    svgPath: "M 550 590 Q 585 580 600 610 Q 585 630 550 620 Z",
    centerX: 572,
    centerY: 605,
  },
  {
    id: "tien-giang",
    name: "Tiền Giang",
    shortName: "TG",
    printName: "Tỉnh Tiền Giang",
    region: "Miền Nam",
    description: "Tỉnh Đồng bằng sông Cửu Long, nổi tiếng với cây ăn quả.",
    specialties: [
      { name: "Xoài Tây Ninh", description: "Xoài thơm ngon từ Tây Ninh", emoji: "🥭" },
      { name: "Mít Tiền Giang", description: "Mít to, ngon từ Vĩnh Kim", emoji: "🌳" },
      { name: "Nhãn Tây Ninh", description: "Nhãn ngọt, đậu giòn", emoji: "🍌" },
    ],
    svgPath: "M 560 620 Q 595 610 610 640 Q 595 660 560 650 Z",
    centerX: 582,
    centerY: 635,
  },
  {
    id: "ben-tre",
    name: "Bến Tre",
    shortName: "BT",
    printName: "Tỉnh Bến Tre",
    region: "Miền Nam",
    description: "Tỉnh Đồng bằng sông Cửu Long, nổi tiếng với dừa và mía.",
    specialties: [
      { name: "Dừa Bến Tre", description: "Dừa xiêm tươi, nước ngọt", emoji: "🥥" },
      { name: "Mía Bến Tre", description: "Mía tươi, nước ngot", emoji: "🍯" },
      { name: "Bánh tráng nướng", description: "Bánh tráng nướng vừng", emoji: "🍨" },
    ],
    svgPath: "M 570 650 Q 605 640 620 670 Q 605 690 570 680 Z",
    centerX: 592,
    centerY: 665,
  },
  {
    id: "tran-an",
    name: "Trà Vinh",
    shortName: "TV",
    printName: "Tỉnh Trà Vinh",
    region: "Miền Nam",
    description: "Tỉnh ven biển Đông Nam Bộ, nổi tiếng với cơm cũng như hải sản.",
    specialties: [
      { name: "Tôm Trà Vinh", description: "Tôm nuôi từ ao tôm địa phương", emoji: "🦐" },
      { name: "Gạo Trà Vinh", description: "Gạo thơm từ vùng Đông Nam", emoji: "🌾" },
      { name: "Mứt Trà Vinh", description: "Mứt từ dâu tây hay mâm xôi", emoji: "🍒" },
    ],
    svgPath: "M 580 680 Q 615 670 630 700 Q 615 720 580 710 Z",
    centerX: 602,
    centerY: 695,
  },
  {
    id: "vinh-long",
    name: "Vĩnh Long",
    shortName: "VL",
    printName: "Tỉnh Vĩnh Long",
    region: "Miền Nam",
    description: "Tỉnh Đồng bằng sông Cửu Long, nổi tiếng với quả chuối và lúa.",
    specialties: [
      { name: "Chuối Vĩnh Long", description: "Chuối chín tự nhiên, ngon", emoji: "🍌" },
      { name: "Xoài Vĩnh Long", description: "Xoài thơm ngon từ vùng", emoji: "🥭" },
      { name: "Gạo Vĩnh Long", description: "Gạo thơm từ vùng ngập nước", emoji: "🌾" },
    ],
    svgPath: "M 560 710 Q 595 700 610 730 Q 595 750 560 740 Z",
    centerX: 582,
    centerY: 725,
  },
  {
    id: "can-tho",
    name: "Cần Thơ",
    shortName: "CT",
    printName: "Thành phố Cần Thơ",
    region: "Miền Nam",
    description: "Thành phố trung tâm Đồng bằng sông Cửu Long.",
    specialties: [
      { name: "Bún mắm Cần Thơ", description: "Món nước mắm thơm đặc trưng của miền Tây", emoji: "🍜" },
      { name: "Lẩu mắm", description: "Lẩu mắm cá linh và bông điên điển", emoji: "🍲" },
      { name: "Bánh xèo miền Tây", description: "Bánh xèo giòn rụm với tôm, giá", emoji: "🥞" },
    ],
    svgPath: "M 550 740 Q 585 730 600 760 Q 585 780 550 770 Z",
    centerX: 572,
    centerY: 755,
  },
  {
    id: "dong-thap",
    name: "Đồng Tháp",
    shortName: "ĐT",
    printName: "Tỉnh Đồng Tháp",
    region: "Miền Nam",
    description: "Tỉnh Đồng bằng sông Cửu Long, nổi tiếng với lúa gạo.",
    specialties: [
      { name: "Gạo Đồng Tháp", description: "Gạo thơm từ vùng 5 gạo", emoji: "🌾" },
      { name: "Mít Đồng Tháp", description: "Mít to, ngon từ vùng", emoji: "🌳" },
      { name: "Lúa mì", description: "Lúa mì từ vùng canh tác", emoji: "🌾" },
    ],
    svgPath: "M 540 760 Q 575 750 590 780 Q 575 800 540 790 Z",
    centerX: 562,
    centerY: 775,
  },
  {
    id: "an-giang",
    name: "An Giang",
    shortName: "AG",
    printName: "Tỉnh An Giang",
    region: "Miền Nam",
    description: "Tỉnh Đồng bằng sông Cửu Long, ven biên giới Campuchia.",
    specialties: [
      { name: "Bún cá Châu Đốc", description: "Bún cá lóc nước lèo đậm đà", emoji: "🍜" },
      { name: "Lẩu mắm An Giang", description: "Lẩu mắm dân giã với cá đồng", emoji: "🍲" },
      { name: "Bánh xèo An Giang", description: "Bánh xèo nhân tôm, thịt", emoji: "🥞" },
      { name: "Cá tra", description: "Cá tra nuôi từ sông Mê Kông", emoji: "🐟" },
      { name: "Gạo An Giang", description: "Gạo thơm từ vùng 5 gạo", emoji: "🌾" },
    ],
    svgPath: "M 530 780 Q 565 770 580 800 Q 565 820 530 810 Z",
    centerX: 552,
    centerY: 795,
  },
  {
    id: "kien-giang",
    name: "Kiên Giang",
    shortName: "KG",
    printName: "Tỉnh Kiên Giang",
    region: "Miền Nam",
    description: "Tỉnh ven biển Miền Nam, nổi tiếng với Phú Quốc và hải sản.",
    specialties: [
      { name: "Tôm hùm Phú Quốc", description: "Tôm hùm tươi sống đắt đỏ", emoji: "🦐" },
      { name: "Cá Phú Quốc", description: "Cá khô từ đảo Phú Quốc", emoji: "🐟" },
      { name: "Hạt tiêu Phú Quốc", description: "Hạt tiêu đen nguyên chất", emoji: "🌶️" },
    ],
    svgPath: "M 510 800 Q 545 790 560 820 Q 545 840 510 830 Z",
    centerX: 532,
    centerY: 815,
  },
  {
    id: "ca-mau",
    name: "Cà Mau",
    shortName: "CM",
    printName: "Tỉnh Cà Mau",
    region: "Miền Nam",
    description: "Tỉnh xa xôi ở đất liền phía Nam của Việt Nam, nổi tiếng với mũi Cà Mau.",
    specialties: [
      { name: "Tôm Cà Mau", description: "Tôm biển tươi sống từ vùng Mũi Cà Mau", emoji: "🦐" },
      { name: "Cua Cà Mau", description: "Cua tinh tú từ biển Cà Mau", emoji: "🦀" },
      { name: "Cá lóc Cà Mau", description: "Cá lóc tươi từ vùng Mũi", emoji: "🐟" },
    ],
    svgPath: "M 500 830 Q 535 820 550 850 Q 535 870 500 860 Z",
    centerX: 522,
    centerY: 845,
  },

  // ===== ĐẢO HOA SA, TRƯỜNG SA =====
  {
    id: "hoang-sa",
    name: "Hoàng Sa",
    shortName: "HS",
    printName: "Quần đảo Hoàng Sa",
    region: "Hải Đảo",
    description: "Quần đảo Hoàng Sa là bộ phận không thể tách rời của Việt Nam.",
    specialties: [
      { name: "Cá biển Hoàng Sa", description: "Cá biển tươi từ vùng biển",emoji: "🐟" },
      { name: "Tôm biển", description: "Tôm biển từ vùng sâu", emoji: "🦐" },
      { name: "Khô cá cơm", description: "Khô cá cơm từ vùng biển", emoji: "🐙" },
    ],
    svgPath: "M 680 200 Q 700 190 710 210 Q 700 220 680 215 Z",
    centerX: 695,
    centerY: 207,
  },
  {
    id: "truong-sa",
    name: "Trường Sa",
    shortName: "TS",
    printName: "Quần đảo Trường Sa",
    region: "Hải Đảo",
    description: "Quần đảo Trường Sa là bộ phận không thể tách rời của Việt Nam.",
    specialties: [
      { name: "Cá biển Trường Sa", description: "Cá biển tươi từ vùng biển", emoji: "🐟" },
      { name: "Tôm hùm", description: "Tôm hùm tươi từ vùng sâu", emoji: "🦐" },
      { name: "Mực biển", description: "Mực tươi từ vùng biển", emoji: "🦑" },
    ],
    svgPath: "M 700 350 Q 720 340 730 360 Q 720 370 700 365 Z",
    centerX: 715,
    centerY: 357,
  },
  // ===== Additional provinces to reach 64 entries =====
  {
    id: "ha-noi",
    name: "Hà Nội",
    shortName: "HN",
    printName: "Thành phố Hà Nội",
    region: "Miền Bắc",
    description: "Thủ đô, trung tâm chính trị và văn hóa của Việt Nam.",
    specialties: [
      { name: "Phở Hà Nội", description: "Bát phở bò thơm lừng với nước dùng trong veo", emoji: "🍜" },
      { name: "Bún chả", description: "Thịt nướng ăn kèm bún và nước mắm chua ngọt", emoji: "🍖" },
      { name: "Chả cá Lã Vọng", description: "Cá chiên ăn với thì là và lạc", emoji: "🐟" },
      { name: "Bánh cuốn", description: "Bánh tráng cuốn nhân thịt mộc nhĩ", emoji: "🍲" },
    ],
    svgPath: "M 420 140 Q 440 130 455 150 Q 440 165 420 160 Z",
    centerX: 440,
    centerY: 145,
  },
  {
    id: "hai-phong",
    name: "Hải Phòng",
    shortName: "HP",
    printName: "Thành phố Hải Phòng",
    region: "Miền Bắc",
    description: "Cảng biển lớn ở miền Bắc, nổi tiếng với hải sản.",
    specialties: [
      { name: "Bún cá Hải Phòng", description: "Bún cá đặc trưng với chả cá và nước dùng đậm đà", emoji: "🍜" },
      { name: "Chả mực", description: "Chả mực thơm giòn được làm từ mực tươi", emoji: "🐙" },
      { name: "Bánh cuốn trứng", description: "Bánh cuốn kèm trứng rắc hành", emoji: "🥚" },
    ],
    svgPath: "M 470 110 Q 490 100 505 120 Q 490 135 470 130 Z",
    centerX: 490,
    centerY: 117,
  },
  {
    id: "hai-duong",
    name: "Hải Dương",
    shortName: "HD",
    printName: "Tỉnh Hải Dương",
    region: "Miền Bắc",
    description: "Tỉnh nông nghiệp gần Hà Nội và Hải Phòng.",
    specialties: [
      { name: "Bánh đậu xanh", description: "Bánh làm từ đậu xanh xay nhuyễn và đường", emoji: "🟩" },
      { name: "Ốc nhồi", description: "Ốc nhồi thịt thơm với mắm gừng", emoji: "🐚" },
      { name: "Bánh gai Hải Dương", description: "Bánh gai nhân ngọt đậm đà", emoji: "🍃" },
    ],
    svgPath: "M 450 125 Q 470 115 485 135 Q 470 150 450 145 Z",
    centerX: 468,
    centerY: 131,
  },
  {
    id: "hung-yen",
    name: "Hưng Yên",
    shortName: "HY",
    printName: "Tỉnh Hưng Yên",
    region: "Miền Bắc",
    description: "Tỉnh nông nghiệp phía nam Hà Nội.",
    specialties: [
      { name: "Nhãn lồng Hưng Yên", description: "Nhãn ngọt nổi tiếng miền Bắc", emoji: "🍈" },
      { name: "Bánh cuốn Hưng Yên", description: "Bánh cuốn ăn kèm chả và hành", emoji: "🍲" },
      { name: "Vải thiều", description: "Vải trái mùa thơm ngọt", emoji: "🍒" },
    ],
    svgPath: "M 435 135 Q 455 125 470 145 Q 455 160 435 155 Z",
    centerX: 452,
    centerY: 142,
  },
  {
    id: "nam-dinh",
    name: "Nam Định",
    shortName: "ND",
    printName: "Tỉnh Nam Định",
    region: "Miền Bắc",
    description: "Tỉnh đồng bằng ven biển với truyền thống ẩm thực phong phú.",
    specialties: [],
    svgPath: "M 445 150 Q 465 140 480 160 Q 465 175 445 170 Z",
    centerX: 462,
    centerY: 156,
  },
  {
    id: "ninh-binh",
    name: "Ninh Bình",
    shortName: "NB",
    printName: "Tỉnh Ninh Bình",
    region: "Miền Bắc",
    description: "Vùng trữ tình với nhiều danh lam thắng cảnh và đặc sản.",
    specialties: [],
    svgPath: "M 410 155 Q 430 145 445 165 Q 430 180 410 175 Z",
    centerX: 430,
    centerY: 160,
  },
  {
    id: "ha-nam",
    name: "Hà Nam",
    shortName: "HN",
    printName: "Tỉnh Hà Nam",
    region: "Miền Bắc",
    description: "Tỉnh nhỏ nằm giữa Hà Nội và Ninh Bình.",
    specialties: [],
    svgPath: "M 425 145 Q 445 135 460 155 Q 445 170 425 165 Z",
    centerX: 445,
    centerY: 150,
  },
  {
    id: "thai-binh",
    name: "Thái Bình",
    shortName: "TB",
    printName: "Tỉnh Thái Bình",
    region: "Miền Bắc",
    description: "Tỉnh đồng bằng ven biển, nổi tiếng với các sản phẩm nông nghiệp.",
    specialties: [],
    svgPath: "M 455 140 Q 475 130 490 150 Q 475 165 455 160 Z",
    centerX: 472,
    centerY: 147,
  },
  {
    id: "lao-cai",
    name: "Lào Cai",
    shortName: "LC",
    printName: "Tỉnh Lào Cai",
    region: "Miền Bắc",
    description: "Tỉnh vùng núi biên giới phía Bắc, nổi tiếng với đào và rau quả vùng cao.",
    specialties: [],
    svgPath: "M 300 60 Q 330 45 350 75 Q 330 95 300 90 Z",
    centerX: 330,
    centerY: 70,
  },
  {
    id: "dak-lak",
    name: "Đắk Lắk",
    shortName: "DL",
    printName: "Tỉnh Đắk Lắk",
    region: "Miền Nam",
    description: "Trung tâm Tây Nguyên, nổi tiếng với cà phê và cao nguyên bạt ngàn.",
    specialties: [],
    svgPath: "M 560 360 Q 590 345 610 380 Q 590 405 560 390 Z",
    centerX: 585,
    centerY: 372,
  },
  {
    id: "dak-nong",
    name: "Đắk Nông",
    shortName: "DN",
    printName: "Tỉnh Đắk Nông",
    region: "Miền Nam",
    description: "Tỉnh Tây Nguyên giáp Đắk Lắk, trồng nhiều cà phê và hồ tiêu.",
    specialties: [],
    svgPath: "M 570 380 Q 600 365 620 395 Q 600 420 570 405 Z",
    centerX: 595,
    centerY: 387,
  },
  {
    id: "lam-dong",
    name: "Lâm Đồng",
    shortName: "LD",
    printName: "Tỉnh Lâm Đồng",
    region: "Miền Nam",
    description: "Tỉnh cao nguyên nổi tiếng với Đà Lạt, hoa và rau quả.",
    specialties: [],
    svgPath: "M 600 400 Q 630 385 650 415 Q 630 440 600 425 Z",
    centerX: 625,
    centerY: 405,
  },
  {
    id: "gia-lai",
    name: "Gia Lai",
    shortName: "GL",
    printName: "Tỉnh Gia Lai",
    region: "Miền Nam",
    description: "Tỉnh Tây Nguyên, nổi tiếng với cà phê và dược liệu.",
    specialties: [],
    svgPath: "M 540 340 Q 570 325 590 355 Q 570 380 540 365 Z",
    centerX: 565,
    centerY: 350,
  },
  {
    id: "kon-tum",
    name: "Kon Tum",
    shortName: "KT",
    printName: "Tỉnh Kon Tum",
    region: "Miền Nam",
    description: "Tỉnh núi cao Tây Nguyên, có nhiều dân tộc thiểu số.",
    specialties: [],
    svgPath: "M 520 320 Q 550 305 570 335 Q 550 360 520 345 Z",
    centerX: 545,
    centerY: 327,
  },
  {
    id: "binh-duong",
    name: "Bình Dương",
    shortName: "BD",
    printName: "Tỉnh Bình Dương",
    region: "Miền Nam",
    description: "Tỉnh công nghiệp gần TP.HCM, phát triển nhanh.",
    specialties: [],
    svgPath: "M 610 540 Q 640 525 660 555 Q 640 580 610 565 Z",
    centerX: 635,
    centerY: 545,
  },
  {
    id: "binh-phuoc",
    name: "Bình Phước",
    shortName: "BP",
    printName: "Tỉnh Bình Phước",
    region: "Miền Nam",
    description: "Tỉnh nằm ở Đông Nam Bộ, nổi tiếng với điều và cao su.",
    specialties: [],
    svgPath: "M 600 560 Q 630 545 650 575 Q 630 600 600 585 Z",
    centerX: 630,
    centerY: 565,
  },
  {
    id: "bac-lieu",
    name: "Bạc Liêu",
    shortName: "BL",
    printName: "Tỉnh Bạc Liêu",
    region: "Miền Nam",
    description: "Tỉnh ven biển Đồng bằng sông Cửu Long, nổi tiếng với tôm và cá.",
    specialties: [],
    svgPath: "M 520 820 Q 550 805 570 835 Q 550 860 520 845 Z",
    centerX: 545,
    centerY: 825,
  },
  {
    id: "soc-trang",
    name: "Sóc Trăng",
    shortName: "ST",
    printName: "Tỉnh Sóc Trăng",
    region: "Miền Nam",
    description: "Tỉnh ven biển Đồng bằng sông Cửu Long, nổi tiếng với đặc sản địa phương.",
    specialties: [],
    svgPath: "M 540 800 Q 570 785 590 815 Q 570 840 540 825 Z",
    centerX: 565,
    centerY: 805,
  },
]
